services:

  main-db:
    image: postgres:16.1
    container_name: ewm-main-service-db-container
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_main_data:/var/lib/postgresql/data
    restart: on-failure

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-service-db-container
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_stats_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  ewm_stats_data:
  ewm_main_data: